"""Generator for run_<slug>.py wrappers.

Given a company name, write a ready-to-run wrapper script with sensible
defaults plus the few fields only you can supply (HQ city, AE name, seed
URLs). The output is just a small Python file that calls the same
pipeline.run() as run_brantley.py — nothing magic.

Usage
-----

Interactive (prompts for the human-only fields):

    python3 new_prospect.py "Quantum Reality Capture"

Non-interactive (everything via flags):

    python3 new_prospect.py "Quantum Reality Capture" \\
        --domain quantumrealitycapture.com \\
        --industry construction \\
        --hq Charleston --state SC \\
        --federal --linkedin --strategist \\
        --alias "Quantum Reality Capture LLC" \\
        --seed-url https://quantumrealitycapture.com/about/ \\
        --seed-url https://www.linkedin.com/company/quantum-reality-capture \\
        --ae "J. Chen" \\
        --no-interactive

Output: writes ./run_<slug>.py and prints the path. Refuses to overwrite
unless --force is passed.
"""

from __future__ import annotations
import argparse
import os
import re
import sys
from datetime import date, timedelta
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parent

VALID_INDUSTRIES = ("construction", "healthcare", "finance", "general", "")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def slugify(name: str) -> str:
    s = name.lower()
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"[\s-]+", "_", s).strip("_")
    return s or "prospect"


def py_repr(value):
    """Format a Python value for inclusion in source code."""
    return repr(value)


def py_tuple(items: Iterable[str]) -> str:
    items = [i for i in items if i]
    if not items:
        return "()"
    return "(\n        " + ",\n        ".join(repr(i) for i in items) + ",\n    )"


def py_list(items: Iterable[str]) -> str:
    items = [i for i in items if i]
    if not items:
        return "[]"
    return "[\n        " + ",\n        ".join(repr(i) for i in items) + ",\n    ]"


# ---------------------------------------------------------------------------
# Interactive prompts
# ---------------------------------------------------------------------------

def ask(prompt: str, *, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    val = input(f"{prompt}{suffix}: ").strip()
    return val or default


def ask_yes_no(prompt: str, *, default: bool = True) -> bool:
    d = "Y/n" if default else "y/N"
    val = input(f"{prompt} [{d}]: ").strip().lower()
    if not val:
        return default
    return val[0] == "y"


def ask_multi(prompt: str, *, label: str = "value") -> list[str]:
    print(f"{prompt}")
    print(f"  Enter one {label} per line. Blank line to finish.")
    out: list[str] = []
    while True:
        v = input(f"  {label} > ").strip()
        if not v:
            break
        out.append(v)
    return out


def ask_industry() -> str:
    print("Industry vertical (gates the BuildZoom/ENR/etc. searches):")
    print("  1) construction (default — also good for AEC services)")
    print("  2) healthcare")
    print("  3) finance")
    print("  4) general (just LinkedIn company page)")
    print("  5) (none)")
    val = input("  Pick 1–5 [1]: ").strip() or "1"
    return {"1": "construction", "2": "healthcare", "3": "finance",
            "4": "general", "5": ""}.get(val, "construction")


# ---------------------------------------------------------------------------
# Template
# ---------------------------------------------------------------------------

TEMPLATE = '''\
"""Drop-in run script for {company}.

Generated by new_prospect.py. Edit any of the constants below and re-run.
"""

from __future__ import annotations
import os
import sys
from datetime import date, timedelta
from pathlib import Path

try:
    from dotenv import load_dotenv, find_dotenv
    load_dotenv(find_dotenv(usecwd=True), override=False)
except ImportError:
    print("note: python-dotenv not installed — .env will not be auto-loaded.",
          file=sys.stderr)

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

os.environ.setdefault("EXTRACTOR_MODEL_OVERRIDE", "gpt-4o-mini")

from pipeline import config  # noqa: E402
if os.environ.get("EXTRACTOR_MODEL_OVERRIDE"):
    config.EXTRACTOR_MODEL = os.environ["EXTRACTOR_MODEL_OVERRIDE"]

from pipeline.pipeline import run as run_pipeline  # noqa: E402

# ---------------------------------------------------------------------------
# Prospect — edit these constants for each company.
# ---------------------------------------------------------------------------

COMPANY = {company!r}
TICKER = {ticker!r}
DOMAIN = {domain!r}
AE = {ae!r}
MEETING_DATE = date.today() + timedelta(days={meeting_offset_days})
OUT_DIR = ROOT / "examples" / {out_slug!r}

COVERAGE_DAYS = {coverage_days}

# Vertical adapters. {industry_comment}
INDUSTRY_KINDS = {industry_kinds}

# LinkedIn leadership discovery (DDG snippets only — no scraping).
INCLUDE_LINKEDIN = {include_linkedin}

# USAspending federal contract record + SAM.gov entity (key-gated).
INCLUDE_FEDERAL = {include_federal}

# Geography / context tokens that uniquely identify the right entity.
# Required when same-name impostors might exist (most B2B prospects).
DISAMBIGUATORS = {disambiguators}

# Alternate / legal entity names. Federal records frequently use the legal
# name not the trade name — without this, USAspending search misses awards.
ALIASES = {aliases}

# Strategist inference layer (revenue triangulation, market position,
# tailored value hooks). Output is clearly labeled [inferred].
RUN_STRATEGIST = {run_strategist}

# Meeting persona: ceo, cto, cfo, coo, cro, or generic. Tailors discovery
# questions and strategist value hooks to the named role.
AUDIENCE = {audience!r}

# Known canonical URLs — your About page, Team page, LinkedIn /company/,
# any aggregator profiles. Each bypasses the relevance gate (exact URL
# trust) and feeds the extractor.
SEED_URLS: list[str] = {seed_urls}


def preflight():
    if not os.environ.get("OPENAI_API_KEY"):
        print("ERROR: set OPENAI_API_KEY before running "
              "(via .env or `export OPENAI_API_KEY=...`).", file=sys.stderr)
        sys.exit(2)


def main():
    preflight()
    print(f"Running prospect_brief on: {{COMPANY}}")
    print(f"  domain         : {{DOMAIN}}")
    print(f"  AE             : {{AE}}")
    print(f"  meeting date   : {{MEETING_DATE.isoformat()}}")
    print(f"  coverage window: {{COVERAGE_DAYS}} days")
    print(f"  extractor model: {{config.EXTRACTOR_MODEL}}")
    print(f"  strategist on  : {{RUN_STRATEGIST}}")
    print(f"  out dir        : {{OUT_DIR}}")
    print()

    vf = run_pipeline(
        company=COMPANY,
        ticker=TICKER,
        domain=DOMAIN,
        ae=AE,
        meeting_date=MEETING_DATE,
        out_dir=OUT_DIR,
        coverage_days=COVERAGE_DAYS,
        industry_kinds=INDUSTRY_KINDS,
        include_linkedin=INCLUDE_LINKEDIN,
        include_federal=INCLUDE_FEDERAL,
        seed_urls=SEED_URLS or None,
        disambiguators=DISAMBIGUATORS,
        aliases=ALIASES,
        strategist=RUN_STRATEGIST,
        audience=AUDIENCE,
    )

    print()
    print(f"Verifier: {{vf.verifier_log.quotes_passed}}/"
          f"{{vf.verifier_log.quotes_checked}} quotes matched. "
          f"{{len(vf.verifier_log.stripped)}} stripped.")
    print()
    print(f"Brief written to: {{OUT_DIR / 'brief.md'}}")
    print(f"Audit trail:      {{OUT_DIR / 'facts.json'}}")
    print(f"Evidence packet:  {{OUT_DIR / 'sources.md'}}")


if __name__ == "__main__":
    main()
'''


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    p = argparse.ArgumentParser(
        description="Generate a run_<slug>.py wrapper for a new prospect.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument("company", help="Display name (e.g. 'Quantum Reality Capture').")
    p.add_argument("--domain", default=None,
                   help="Company website domain (e.g. quantumrealitycapture.com).")
    p.add_argument("--ticker", default=None, help="Stock ticker if public.")
    p.add_argument("--ae", default="Account Executive",
                   help="AE name (default: 'Account Executive' — change before sending).")
    p.add_argument("--industry", default=None,
                   choices=("construction", "healthcare", "finance", "general"),
                   help="Vertical adapter to enable.")
    p.add_argument("--hq", default=None, help="HQ city (used as disambiguator).")
    p.add_argument("--state", default=None,
                   help="HQ state abbreviation (e.g. 'SC') used as disambiguator.")
    p.add_argument("--alias", action="append", default=[],
                   help="Alternate / legal entity name. Repeat for multiple.")
    p.add_argument("--seed-url", action="append", default=[],
                   help="Known URL to seed (repeat for multiple).")
    p.add_argument("--linkedin", action=argparse.BooleanOptionalAction, default=True,
                   help="Run LinkedIn leadership discovery.")
    p.add_argument("--federal", action=argparse.BooleanOptionalAction, default=True,
                   help="Pull USAspending + SAM.gov.")
    p.add_argument("--strategist", action=argparse.BooleanOptionalAction, default=True,
                   help="Run inference layer (revenue triangulation, hooks).")
    p.add_argument("--audience", default="generic",
                   choices=("ceo", "cto", "cfo", "coo", "cro", "generic"),
                   help="Meeting persona — tailors questions and hooks.")
    p.add_argument("--coverage-days", type=int, default=540,
                   help="How far back to look (default 540 = 18 months).")
    p.add_argument("--meeting-offset-days", type=int, default=2,
                   help="Default meeting date offset from today.")
    p.add_argument("--out", default=None,
                   help="Output Python file path (default: run_<slug>.py in cwd).")
    p.add_argument("--force", action="store_true",
                   help="Overwrite existing file.")
    p.add_argument("--no-interactive", action="store_true",
                   help="Skip prompts; use only flag values.")

    args = p.parse_args()

    company = args.company.strip()
    if not company:
        print("ERROR: company name required.", file=sys.stderr)
        sys.exit(2)

    interactive = not args.no_interactive

    domain = args.domain
    if interactive and not domain:
        domain = ask("Company website domain (no http://)",
                     default="").strip().rstrip("/")
        if domain.startswith("http"):
            from urllib.parse import urlparse
            domain = urlparse(domain).hostname or domain

    ae = args.ae
    if interactive:
        ae = ask("AE name", default=ae)

    industry = args.industry
    if interactive and not industry:
        industry = ask_industry()
    industry_kinds = (industry,) if industry else ()
    industry_comment = (
        f"'{industry}' pulls vertical-database queries via DDG."
        if industry else "No vertical adapter enabled."
    )

    hq = args.hq
    state = args.state
    if interactive:
        if not hq:
            hq = ask("HQ city (used as disambiguator; e.g. 'Charleston')",
                     default="")
        if not state:
            state = ask("State abbreviation (e.g. 'SC')", default="")
    disambiguators = tuple(d.lower() for d in (hq, state) if d)

    aliases = list(args.alias)
    if interactive and not aliases:
        if ask_yes_no("Add alternate / legal entity names? "
                      "(strongly recommended for federal-search recall)",
                      default=True):
            aliases = ask_multi("", label="alias")

    seed_urls = list(args.seed_url)
    if interactive and not seed_urls:
        print()
        print("Seed URLs — at minimum: their About page, Team page, LinkedIn")
        print("/company/ page. More URLs = richer brief.")
        seed_urls = ask_multi("Paste known URLs", label="url")

    # Output path
    slug = slugify(company)
    out_path = Path(args.out) if args.out else (ROOT / f"run_{slug}.py")
    if out_path.exists() and not args.force:
        print(f"ERROR: {out_path} already exists. Pass --force to overwrite.",
              file=sys.stderr)
        sys.exit(2)

    # Render
    rendered = TEMPLATE.format(
        company=company,
        ticker=args.ticker,
        domain=domain,
        ae=ae,
        meeting_offset_days=args.meeting_offset_days,
        out_slug=slug.upper(),
        coverage_days=args.coverage_days,
        industry_comment=industry_comment,
        industry_kinds=py_tuple(industry_kinds),
        include_linkedin=args.linkedin,
        include_federal=args.federal,
        disambiguators=py_tuple(disambiguators),
        aliases=py_tuple(aliases),
        run_strategist=args.strategist,
        audience=args.audience,
        seed_urls=py_list(seed_urls),
    )

    out_path.write_text(rendered)
    print()
    print(f"  → wrote {out_path}")
    print()
    print(f"Next: python3 {out_path.name}")


if __name__ == "__main__":
    main()
