"""Drop-in run script for Quantum Reality Capture.

Generated by new_prospect.py. Edit any of the constants below and re-run.
"""

from __future__ import annotations
import os
import sys
from datetime import date, timedelta
from pathlib import Path

try:
    from dotenv import load_dotenv, find_dotenv
    load_dotenv(find_dotenv(usecwd=True), override=False)
except ImportError:
    print("note: python-dotenv not installed — .env will not be auto-loaded.",
          file=sys.stderr)

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

os.environ.setdefault("EXTRACTOR_MODEL_OVERRIDE", "gpt-4o-mini")

from pipeline import config  # noqa: E402
if os.environ.get("EXTRACTOR_MODEL_OVERRIDE"):
    config.EXTRACTOR_MODEL = os.environ["EXTRACTOR_MODEL_OVERRIDE"]

from pipeline.pipeline import run as run_pipeline  # noqa: E402

# ---------------------------------------------------------------------------
# Prospect — edit these constants for each company.
# ---------------------------------------------------------------------------

COMPANY = 'Quantum Reality Capture'
TICKER = None
DOMAIN = 'quantumrealitycapture.com'
AE = 'Spenser'
MEETING_DATE = date.today() + timedelta(days=2)
OUT_DIR = ROOT / "examples" / 'QUANTUM_REALITY_CAPTURE'

COVERAGE_DAYS = 540

# Vertical adapters. 'construction' pulls vertical-database queries via DDG.
INDUSTRY_KINDS = (
        'construction',
    )

# LinkedIn leadership discovery (DDG snippets only — no scraping).
INCLUDE_LINKEDIN = True

# USAspending federal contract record + SAM.gov entity (key-gated).
INCLUDE_FEDERAL = True

# Geography / context tokens that uniquely identify the right entity.
# Required when same-name impostors might exist (most B2B prospects).
DISAMBIGUATORS = (
        'charleston',
        'sc',
    )

# Alternate / legal entity names. Federal records frequently use the legal
# name not the trade name — without this, USAspending search misses awards.
ALIASES = ()

# Strategist inference layer (revenue triangulation, market position,
# tailored value hooks). Output is clearly labeled [inferred].
RUN_STRATEGIST = True

# Known canonical URLs — your About page, Team page, LinkedIn /company/,
# any aggregator profiles. Each bypasses the relevance gate (exact URL
# trust) and feeds the extractor.
SEED_URLS: list[str] = [
        'https://quantumrealitycapture.com/about/',
        'https://quantumrealitycapture.com/team/',
        'https://www.linkedin.com/company/quantum-reality-capture',
        'https://www.qrcgov.com/',
    ]


def preflight():
    if not os.environ.get("OPENAI_API_KEY"):
        print("ERROR: set OPENAI_API_KEY before running "
              "(via .env or `export OPENAI_API_KEY=...`).", file=sys.stderr)
        sys.exit(2)


def main():
    preflight()
    print(f"Running prospect_brief on: {COMPANY}")
    print(f"  domain         : {DOMAIN}")
    print(f"  AE             : {AE}")
    print(f"  meeting date   : {MEETING_DATE.isoformat()}")
    print(f"  coverage window: {COVERAGE_DAYS} days")
    print(f"  extractor model: {config.EXTRACTOR_MODEL}")
    print(f"  strategist on  : {RUN_STRATEGIST}")
    print(f"  out dir        : {OUT_DIR}")
    print()

    vf = run_pipeline(
        company=COMPANY,
        ticker=TICKER,
        domain=DOMAIN,
        ae=AE,
        meeting_date=MEETING_DATE,
        out_dir=OUT_DIR,
        coverage_days=COVERAGE_DAYS,
        industry_kinds=INDUSTRY_KINDS,
        include_linkedin=INCLUDE_LINKEDIN,
        include_federal=INCLUDE_FEDERAL,
        seed_urls=SEED_URLS or None,
        disambiguators=DISAMBIGUATORS,
        aliases=ALIASES,
        strategist=RUN_STRATEGIST,
    )

    print()
    print(f"Verifier: {vf.verifier_log.quotes_passed}/"
          f"{vf.verifier_log.quotes_checked} quotes matched. "
          f"{len(vf.verifier_log.stripped)} stripped.")
    print()
    print(f"Brief written to: {OUT_DIR / 'brief.md'}")
    print(f"Audit trail:      {OUT_DIR / 'facts.json'}")
    print(f"Evidence packet:  {OUT_DIR / 'sources.md'}")


if __name__ == "__main__":
    main()
